/**
 * Read version info generated by scripts/bump-build.js during prebuild.
 * Returns null if version-info.json not found (e.g. dev without build).
 */

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));

// Process start time — lets operators detect stale server processes.
// If the running PID started before the build time, the server needs a restart.
const PROCESS_START = new Date().toISOString();

export function readVersionInfo() {
  try {
    // version-info.json lives in packages/cli/assets/ (generated by copy-cli-assets.mjs)
    // __dirname = dist/server/ → go up two levels to packages/cli/, then into assets/
    const filePath = join(__dirname, "..", "..", "assets", "version-info.json");
    const raw = readFileSync(filePath, "utf8");
    const info = JSON.parse(raw);
    // Attach process start time so the API consumer can verify this process
    // was launched AFTER the build (i.e. it is running the latest code).
    return { ...info, processStartedAt: PROCESS_START };
  } catch {
    return null;
  }
}
