/**
 * Read version info generated by scripts/bump-build.js during prebuild.
 * Returns null if version-info.json not found (e.g. dev without build).
 */

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));

export function readVersionInfo() {
  try {
    // version-info.json lives in packages/cli/assets/ (generated by copy-cli-assets.mjs)
    // __dirname = dist/server/ → go up two levels to packages/cli/, then into assets/
    const filePath = join(__dirname, "..", "..", "assets", "version-info.json");
    const raw = readFileSync(filePath, "utf8");
    return JSON.parse(raw);
  } catch {
    return null;
  }
}
